NUPLAN_DATA_ROOT: "/home/kevin/MTGS/data/nuplan/dataset/nuplan-v1.1/splits/mini/data/cache/mini"
NUPLAN_DB_FILES: "/home/kevin/MTGS/data/nuplan/dataset/nuplan-v1.1/splits/mini/data/cache/mini"
NUPLAN_SENSOR_ROOT: "/home/kevin/MTGS/data/sensor_blobs"
NUPLAN_MAPS_ROOT: "/mnt/scratchdata/navsim_data/maps"
NUPLAN_MAP_VERSION: "nuplan-maps-v1.0"
